version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocritic
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - nilnil
    - noctx
    - prealloc
    - reassign
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
    gosec:
      excludes:
        - G101
        - G112
        - G115
        - G204
        - G402
        - G404
        - G501
        - G505
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - composites
        - copylocks
        - fieldalignment
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - unmarshal
        - unreachable
        - unusedresult
      disable-all: true
    reassign:
      patterns:
        - .*
    staticcheck:
      checks:
        - -SA1019
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*Mock.*
      - .*_mock.*
      - .*test.*
      - .*mock.*
      - .*example.*
      - .*utils.*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - .*Mock.*
      - .*_mock.*
      - .*test.*
      - .*mock.*
      - .*example.*
      - .*utils.*
      - third_party$
      - builtin$
      - examples$
