run:
  timeout: 5m
  tests: false
  skip-dirs:
    - ".*test.*"
    - ".*mock.*"
    - ".*example.*"
    - ".*utils.*"
  skip-files:
    - ".*Mock.*"
    - ".*_mock.*"

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    # Default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Custom
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - forcetypeassert
    - gocritic
    - goerr113
    - gofumpt
    - gosec
    - importas
    - makezero
    - nilnil
    - noctx
    - prealloc
    - reassign
    # - rowserrcheck
    - sqlclosecheck
    - unconvert
    # - wastedassign
  fast: true

linters-settings:
  # Default
  govet:
    check-shadowing: false
    disable-all: true
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
      - fieldalignment
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - unmarshal
      - unreachable
      - unusedresult
  staticcheck:
    checks: ["all", "-SA1019"]
  # Custom
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - unnamedResult
      - whyNoLint
    enabled-tags:
      - diagnostic
      - style
  gosec:
    excludes:
      - G101
      - G112
      - G402
      - G404
      - G501
      - G505
    exclude-generated: true
  reassign:
    patterns:
      - ".*"
